In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
from sklearn.model_selection import KFold, train_test_split

In [6]:
data = pd.read_parquet('d:/BankCustomer/data/bank_v3.parquet')
df = data.copy()

In [7]:
df.head().T

0         1         2         3         4
age                     59.0      56.0      41.0      55.0      54.0
job                      0.0       0.0       9.0       7.0       0.0
marital                  1.0       1.0       1.0       1.0       1.0
education                2.0       2.0       2.0       2.0       3.0
default                  0.0       0.0       0.0       0.0       0.0
balance             234300.0    4500.0  127000.0  247600.0   18400.0
yearly_income       234567.0  307600.0  500000.0  234000.0  327600.0
number_of_children       0.0       4.0       0.0       3.0       1.0
housing                  1.0       0.0       1.0       1.0       0.0
loan                     0.0       0.0       0.0       0.0       0.0
contact                  2.0       2.0       2.0       2.0       2.0
day                      5.0       5.0       5.0       5.0       5.0
duration              1042.0    1467.0    1389.0     579.0     673.0
campaign                 1.0       1.0       1.0       1.0       2.0
pdays                   -1.0      -1.0      -1.0      -1.0      -1.0
previous                 0.0       0.0       0.0       0.0       0.0
poutcome                 3.0       3.0       3.0       3.0       3.0
deposit                  1.0       1.0       1.0       1.0       1.0

<center><h1>Split Data</h1></center>

In [14]:
splitter = KFold(n_splits=5, shuffle=True, random_state=33)
folds = list(splitter.split(df))

In [20]:
folds[0]

(array([    0,     1,     2, ..., 11157, 11158, 11159]),
 array([   10,    18,    32, ..., 11146, 11150, 11153]))

In [17]:
folds[2]

(array([    0,     1,     2, ..., 11155, 11156, 11158]),
 array([   31,    36,    38, ..., 11152, 11157, 11159]))

In [19]:
df.loc[folds[0][0]]

age  job  marital  education  default  balance  yearly_income  \
0       59    0        1          2        0   234300  234567.000000   
1       56    0        1          2        0     4500  307600.000000   
2       41    9        1          2        0   127000  500000.000000   
3       55    7        1          2        0   247600  234000.000000   
4       54    0        1          3        0    18400  327600.000000   
...    ...  ...      ...        ...      ...      ...            ...   
11155   35    1        1          2        0     8000   89840.000000   
11156   34    1        2          2        0     -720    8085.600098   
11157   33    1        2          1        0      100    1123.000000   
11158   39    7        1          2        0    73300   82315.000000   
11159   32    9        2          2        0     2900   32567.000000   

       number_of_children  housing  loan  contact  day  duration  campaign  \
0                       0        1     0        2    5      1042         1   
1                       4        0     0        2    5      1467         1   
2                       0        1     0        2    5      1389         1   
3                       3        1     0        2    5       579         1   
4                       1        0     0        2    5       673         2   
...                   ...      ...   ...      ...  ...       ...       ...   
11155                   2        1     1        0   21        38         2   
11156                   0        1     0        0    7       273         5   
11157                   0        1     0        0   20       257         1   
11158                   0        0     0        2   16        83         4   
11159                   0        0     0        0   19       156         2   

       pdays  previous  poutcome  deposit  
0         -1         0         3        1  
1         -1         0         3        1  
2         -1         0         3        1  
3         -1         0         3        1  
4         -1         0         3        1  
...      ...       ...       ...      ...  
11155    172         2         0        0  
11156     -1         0         3        0  
11157     -1         0         3        0  
11158     -1         0         3        0  
11159     -1         0         3        0  

[8928 rows x 18 columns]

In [21]:
d_folds = {}
fold = 0
for train_index, test_index in folds:
    d_folds[f'fold_{fold}_train'] = train_index
    d_folds[f'fold_{fold}_test'] = test_index
    fold += 1

In [22]:
d_folds

{'fold_0_train': array([    0,     1,     2, ..., 11157, 11158, 11159]),
 'fold_0_test': array([   10,    18,    32, ..., 11146, 11150, 11153]),
 'fold_1_train': array([    0,     1,     2, ..., 11156, 11157, 11159]),
 'fold_1_test': array([    5,     8,    12, ..., 11149, 11154, 11158]),
 'fold_2_train': array([    0,     1,     2, ..., 11155, 11156, 11158]),
 'fold_2_test': array([   31,    36,    38, ..., 11152, 11157, 11159]),
 'fold_3_train': array([    0,     1,     3, ..., 11157, 11158, 11159]),
 'fold_3_test': array([    2,     7,     9, ..., 11134, 11138, 11156]),
 'fold_4_train': array([    2,     5,     7, ..., 11157, 11158, 11159]),
 'fold_4_test': array([    0,     1,     3, ..., 11147, 11148, 11155])}

In [23]:
np.savez('d:/BankCustomer/data/folds.npz', **d_folds)

In [24]:
indexes = np.load('d:/BankCustomer/data/folds.npz')

In [25]:
indexes.files

['fold_0_train',
 'fold_0_test',
 'fold_1_train',
 'fold_1_test',
 'fold_2_train',
 'fold_2_test',
 'fold_3_train',
 'fold_3_test',
 'fold_4_train',
 'fold_4_test']

In [26]:
indexes['fold_0_train']

array([    0,     1,     2, ..., 11157, 11158, 11159])